length_in_x: 10.0
length_in_y: 10.0
position_x: 0.0
position_y: 0.0
resolution: 0.1
min_variance: 0.0001
max_variance: 10000.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.00002

# 扫描持续时间，设置小一些减少延迟
scanning_duration: 0.05
